apiVersion: v1
kind: Pod
metadata:
  name: gee-ebs
  labels:
    app: gee
spec:
  containers:
  - image: jyjl1314/geserver:v1
    name: gee
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: "/opt/google/gehttpd/htdocs/cutter/globes/"
      name: nfsvol
    - mountPath: "/var/opt/google/pgsql/data/"
      name: ebsvol
  volumes:
  - name: nfsvol
    persistentVolumeClaim:
      claimName: nfs-pvc
  - name: ebsvol
      hostPath: /data
